module.exports = {
    AdminEmployee: require('./adminEmployees'),
    CartItemLocation: require('./cartItemLocation'),
    CartItems: require('./cartItems'),
    Cart: require('./carts'),
    Commission: require('./commissions'),
    Counter: require('./counters'),
    Discount: require('./discounts'),
    Employee: require('./employees'),
    Invoice: require('./invoices'),
    LicenseePayout: require('./licenseePayouts'),
    Licensee: require('./licensees'),
    Notification: require('./notifications'),
    RentalItemType: require('./rentalItemTypes'),
    TrailerBlocking: require('./trailerBlocking'),
    TrailerInsurance: require('./trailerInsurance'),
    TrailerRating: require('./trailerRatings'),
    TrailerReview: require('./trailerReviews'),
    TrailerServicing: require('./trailerServicing'),
    TrailerType: require('./trailerTypes'),
    Trailer: require('./trailers'),
    UpsellItemType: require('./upsellItemTypes'),
    UpsellItem: require('./upsellItems'),
    User: require('./users')
};